version: '3.9'

services:

  backend:
    # build:
    #   context: ./
    image: ghcr.io/davidt58/test:latest-tagged-version
    ports:
      - 8080:8080
    environment:
      - "PORT=8080"
    container_name: backend

