version: '3.8'
services:

  backend:
    container_name: backend
    image: ghcr.io/davidt58/test:latest-tagged-version
    networks:
      - nginx

networks:
  nginx:
    external: true
    name: nginx
