name: docker-compose-github-actions

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u davidt58 --password-stdin
          docker build . -t ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
          docker push ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/checkout@v2

      - name: Add SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: 'placeholder'
      
      - name: Add SSH key to known hosts
        shell: bash
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        
      - name: Deploy image to ec2
        shell: bash
        env:
          HOST: ${{ secrets.SERVER_IP }}
        run: |
          sed -i "s/latest-tagged-version/$GITHUB_RUN_NUMBER/g" docker-compose.yaml
          scp docker-compose.yaml ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu
          DOCKER_HOST="ssh://ubuntu@${{ secrets.SERVER_IP }}" docker-compose up -d
