name: docker-compose-github-actions

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u davidt58 --password-stdin
          docker build . -t ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
          docker push ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
      - name: Deploy image to ec2
        shell: bash
        run: |
          mkdir .ssh
          echo ${{ secrets.SSH_KEY }} > .ssh/id_rsa
          chmod 400 .ssh/id_rsa
          sed -i "s/latest-tagged-version/$GITHUB_RUN_NUMBER/g" docker-compose.yaml
          scp -i key $SSH_OPTIONS docker-compose.yaml ubuntu@{{ secrets.SERVER_IP }}:/home/ubuntu
          DOCKER_HOST="ssh://ubuntu@{{ secrets.SERVER_IP }}" docker-compose up -d
