name: docker-compose-github-actions

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u davidt58 --password-stdin
          docker build . -t ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
          docker push ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
      - name: Deploy image to ec2
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          chmod +x .github/script.sh
          .github/script.sh
