name: docker-compose-github-actions

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Docker build
        run: |
          docker login -u davidt58 -p $ACCESS_TOKEN
          docker build ./ -t ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
          docker push ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
