name: docker-compose-github-actions

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u davidt58 --password-stdin
          docker build . -t ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
          docker push ghcr.io/davidt58/test:$GITHUB_RUN_NUMBER
      - name: Deploy image to ec2
        run: |
          echo ${{ secrets.SSH_KEY }} >> key
          sed -i "s/latest-tagged-version/$GITHUB_RUN_NUMBER/g" docker-compose.yaml
          scp -i key docker-compose.yaml ubuntu@18.192.4.4:/home/ubuntu
          ssh -i key ubuntu@18.192.4.4 "cd /home/ubuntu/ && docker-compose up -d"
